columns:
  cycle_count: {type: int, min: 0, max: 10000}
  avg_temperature: {type: float, min: 0, max: 100}
  charge_rate: {type: float, min: 0.1, max: 5}
  discharge_rate: {type: float, min: 0.1, max: 5}
  depth_of_discharge: {type: float, min: 0, max: 100}
  internal_resistance: {type: float, min: 0, max: 1}
  state_of_health: {type: float, min: 0, max: 100}